common:
  lid_topic: "/os1_cloud_node/points"
  imu_topic: "/os1_cloud_node/imu"
  camera_topic: "/camera/infra1/image_rect_raw"
  camera_enable: true
  scan_interval: 0.1
  lidar_time_offset: 0
  camera_time_offset: 0
  image_skip: 3
preprocess:
  lidar_type: OUSTER
  blind: 4

mapping:
  acc_cov:       6.0e-2
  gyr_cov:       5.0e-3
  b_acc_cov:     8.0e-5
  b_gyr_cov:     3.0e-6
  fov_degree:    360
  det_range:     100.0
  extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic
  extrin_t_il: [ -0.006253, 0.011775, -0.028535 ]
  extrin_R_il: [ 0.0, 0.0, -1.0, 0.0 ] # (qx, qy, qz, qw)

publish:
  path_publish_en: false
  scan_publish_en: true       # false: close all the point cloud output
  scan_effect_pub_en: true    # true: publish the pointscloud of effect point
  dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
  scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

path_save_en: true                 # 保存轨迹，用于精度计算和比较

pcd_save:
  pcd_save_en: true
  interval: 500                 # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
image_save_en: false

feature_extract_enable: false
point_filter_num: 1
max_iteration: 3
scan_filter_size: 0.2
map_filter_size: 0.2             # 暂时未用到，代码中为0， 即倾向于将降采样后的scan中的所有点加入map
cube_side_length: 1000

ivox_grid_resolution: 0.2        # default=0.2
ivox_nearby_type: 18             # 6, 18, 26
esti_plane_threshold: 0.1        # default=0.1


cam:
  # pinhole
  # pinhole_radial
  # pinhole_fisheye
  # spherical
  camera_model: pinhole_radial
  distortion_param: [0.007017508922248575, -0.002598448110748391, 0.0, -0.0014755213248257705, 0.0006640775125219394]
  pinhole_param: [431.3873911369959, 430.2496176152663, 427.4407802012019, 238.52694867508183]
  resolution: [848, 480]
  extrin_t_ic: [ -0.006253, 0.011775, -0.028535 ]
  extrin_R_ic: [ 0.0, 0.0, -1.0, 0.0 ] # (qx, qy, qz, qw)